// ---------------------------------------------------------------
// FishSilhouetteMask — canonical binary silhouette mask of the fish
// derived from public/fish/template-ikan.png / template-ikan.svg.
//
// Canonical template canvas: 1492 × 1054
// Template outer frame: x=30..1462 (w=1432), y=30..1024 (h=994)
// Fish bounding box: x=266..1225 (w=960), y=220..833 (h=614)
//
// Stored as base64-encoded Uint16Array of alternating run lengths (RLE):
// starts with count of 0s (background), then 1s (fish), etc.
// ---------------------------------------------------------------

export const TEMPLATE_CANONICAL = {
  width: 1492,
  height: 1054,
  frame: {
    x0: 30,
    y0: 30,
    x1: 1462,
    y1: 1024,
    width: 1432,
    height: 994,
    aspect: 1432 / 994, // 1.44064386
  },
  fish: {
    x0: 266,
    y0: 220,
    x1: 1225,
    y1: 833,
    width: 960,
    height: 614,
    aspect: 960 / 614, // 1.5635179
  },
} as const

const MASK_RLE_B64 = 'rAEYAKIDIgCZAyoAkgMwAIwDNgCHAzoAgwM+AH8DQgB7A0YAeANJAHQDTQBxA1AAbgNTAGsDVQBpA1gAZQNbAGQDXQBhA18AXwNiAFwDZABaA2YAWQNoAFYDagBUA2wAUwNuAFADcABPA3IATAN0AEsDdgBIA3kARgN6AEUDfABCA38AQAOBAD4DhAA7A4YAOAOKADUDjQAyA5AALwOUACsDmQAmA58AIAOnABgDrwAPA7cACAO9AAIDwgD9AscA+ALLAPQCzwDwAtMA7ALWAOkC2ADnAtsA5QLcAOMC3gDhAuAA3wLiAN0C4wDcAuUA2gLnANgC6ADYAukA1gLqANUC7ADTAu0A0gLvANAC8ADQAvAAzwLxAM4C8wDMAvQAzAL0AMsC9QDKAvYAyQL3AMkC+ADHAvkAxgL6AMYC+gDFAvwAwwL9AMMC/gDBAgABvwIBAb8CAgG9AgQBuwIGAboCBwG4AgoBtgIMAbMCDwGwAhMBrQIVAaoCGQGnAhwBowIgAZ8CJAGcAiYBmQIqAZYCLQGSAjABkAIzAYwCNgGKAjgBhwI7AYQCPgGCAkABfwJCAX0CRAF3AkoBcgJPAW0CVAFoAlkBYwJeAV8CYQFbAmYBVwJpAVMCbgFPAnEBTAJ0AUkCdwFGAnsBQgJ+AT8CgQE8AoQBOQKHATYCigE0AowBMQKPAS8CkQEsApQBKgKWAScCmAEmApoBIwKdASYBFwDkAJ8BHQEnANsAoQEXATEA1ACjARIBOQDQAKUBDgE/AMwApwEKAUQAyQCoAQcBSQDGAKoBAwFOAMMArAEAAVEAwQCuAf0AVAC/AK8B+wBYALwAsQH5AFoAugCzAfYAXQC4ALQB9QBfALYAtgHyAGEAtQC4AfAAYwCzALkB7wBlALEAuwHtAGYAsAC8AesAaQCuAL4B6QBqAK4AvwHnAGwArADAAeYAbQCrAMIB5QBuAKkAwwHkAG8AqQDEAeIAcQCnAMUB4QByAKYAxwHgAHMApQDIAd4AdACkAMkB3QB2AKIAywHcAHcAoQDLAdsAeACgAM0B2gB5AJ8AzQHZAHoAngDPAdgAewCdAM8B1wB9AJsA0QHWAH0AmwDRAdYAfgCZANMB1AB/AJkA0wHUAIAAlwDVAdMAgQCWANUB0gCCAJUA1gHSAIMAlADXAdEAhACTANcB0QCEAJIA2gHOAIYAkQDdAcsAhwCQAN8ByQCHAI8A4wHGAIgAjgDmAcMAiQCNAOgBwQCJAIwA7AG9AIsAiwDuAbsAjACKAPEBuACNAIgA9AG2AI0AiAD3AbMAjgCHAPkBsQCPAIYA/AGuAI8AhQD/AawAkACEAAICqQCRAIMABAKnAJIAggAHAqQAkgCCAAkCogCTAIAADQKfAJQAfwAPAp0AlQB+ABICmgCVAH4AFAKYAJYAfQAXApUAlwB8ABkCkwCXAHwAHAKRAJcAegAfAo8AmAB5ACECjQCZAHgAJAKKAJkAeAAmAogAmgB3ACkChQCbAHYAKwKDAJwAdQAuAoAAnAB1ADACfwCcAHQAMwJ8AJ0AcwA1AnoAngBxADgCeACeAHEAOwJ1AJ8AcAA9AnMAoABvAEACcQCfAG8AQgJvAKAAbgBEAm0AoQBtAEcCagCiAGwASQJoAKIAbABMAmYAogBrAE4CZACjAGoAUQJhAKQAaQBTAl8ApABpAFUCXQClAGgAWAJbAKUAZwBaAlkApQBnAF0CVgCmAGYAXwJUAKcAZQBhAlIApwBlAGQCUACnAGQAZgJOAKgAYwBpAksAqABjAGsCSQCpAGMAbAJIAKkAYgBvAkUAqQBiAHECQwCqAGEAdAJAAKsAYAB2Aj8AqgBgAHkCPACrAF8AewI6AKsAXwB9AjgArABeAIACNgCsAF0AggI0AKwAXQCFAjEArQBdAIYCLwCtAF0AiAItAK4AXACLAisArQBcAI0CKQCuAFsAkAImAK8AWgCSAiQArwBaAJUCIQCwAFkAlwIfALAAWgCZAhwAsQBZAJwCGQCxAFkAnwIWALIAWACiAhMAsgBYAKUCEACzAFcAqAIMALQAWACsAgQAuABXAGgDVwBpA1YAaQNWAGoDVgBpA1YAaQNWAGoDVQBqA1UAawNVAGoDVQBqA1UAawNUAGsDVQBrA1QAawNUAGsDVABsA1QAawNUAGsDVABrA1QAbANUAGsDVABrA1QAbANUAGsDVABrA1QAawNUAGwDVABrA1QAawNUAGsDVQBqA1UAawNUAGsDVQBqA1UAagNVAGoDVgBpA1YAagNVAGoDVgBpA1YAaQNWAGkDVwBoA1cAaANXAGgDWABnA1gAZwNYAGcDWQBnA1gAZwNZAGYDWQBmA1kAZgNaAGUDWgBmA1oAZwNYAGkDVgBrA1UAbANTAG4DUgBvA1AAcQNPAHIDTQB0A0wAdQNKAHYDSgB3A0gAeQNHAHoDRgB7A0UAfANEAH0DQwB+A0IAfwNBAIADQACBAz8AgQM/AIIDPgCDAz4AgwM9AIQDPACEAz0AhAM8AIUDPACFAzwAhQM7AIUDPACFAzwAhQM8AIUDPACEAzwAhQM7AIYDOgCGAzkAiAM4AIkDNwCJAzcAigM2AIsDNQCLAzUAjAM0AIwDNQCMAzQAjQMzAI0DNACNAzMAjQM0AI0DNACMAzQAjQM0AIwDNQCMAzUAiwM1AIwDNQCLAzYAiwM1AIsDNgCLAzYAigM3AMwCBgC4ADcAyAIMALUANwDGAg8AtQA3AMMCEwCzADgAwQIVALMAOAC+AhgAsgA5ALsCGwCxADkAugIdALEAOQC3AiAAsAA6ALUCIgCwADoAsgIkALAAOwCwAiYArwA8AK0CKQCvADwAqwIrAK4APQCpAi0ArgA9AKYCMACtAD0ApQIyAKwAPgCjAjQArAA+AKACNgCsAD8AngI4AKsAQACcAjoAqwBAAJkCPQCqAEEAlwI/AKkAQgCVAkEAqQBCAJICQwCpAEMAkAJFAKgARACOAkcApwBFAIwCSQCnAEUAiQJMAKYARgCHAk4ApQBHAIUCTwCmAEcAggJSAKUASACAAlQApABJAH4CVgCjAEoAewJZAKMASwB4AloAowBMAHYCXACiAE0AcwJfAKIATQBxAmEAoQBOAG8CYwCgAE8AbAJmAJ8AUABqAmcAoABQAGgCaQCfAFEAZgJrAJ4AUwBiAm4AngBTAGACcACdAFQAXgJyAJwAVQBbAnUAmwBWAFkCdwCbAFYAVwJ4AJsAWABTAnsAmgBZAFECfQCaAFkATwJ/AJkAWgBMAoIAmABcAEkChACXAF0ARwKGAJcAXQBEAokAlgBeAEICiwCVAGAAPwKNAJUAYAA9Ao8AlABhADoCkgCTAGMANwKUAJIAZAA1ApYAkgBkADICmQCRAGYALwKbAJAAZwAtAp0AjwBoACsCnwCPAGkAKwKeAI4AagAtApwAjQBsAC4CmgCNAGwAMAKZAIsAbQAyApcAigBvADMClQCKAG8ANQKTAIkAcQA1ApIAiAByADcCkACIAHMANgKRAIYAdAA3ApAAhgB1ADYCkACFAHcANQKQAIQAeAA1ApEAgwB5ADQCkQCCAHoANAKRAIIAewAyApMAgAB9ADECkwB/AH4AMAKVAH4AfwAuApYAfQCBACwClwB9AIEALAKYAHsAgwAqApoAegCEACgCmwB5AIYAJgKdAHgAhgAlAp4AdwCIACMCoAB2AIkAIQKiAHQAiwAfAqQAcwCMAB0CpQByAI4AGgKoAHEAjwAYAqoAbwCRABYCrABuAJEAFQKuAGwAkwASArEAagCVABACtABnAJgADQK2AGUAmgAKArkAYwCcAAgCvABgAJ4ABgK+AF4AoAADAsIAWwCiAAECxQBXAKUA/gHJAFMAqQD7Ac0ATgCsAPgB0QBKAK8A9gHWAEQAsgDzAdsAPQC4AO8B4gAyAL8A7QHpACQAyQDpAdkB5wHcAeMB3wHgAeMB3QHmAdkB6QHXAewB0wHwAdAB8wHMAfcByAH7AcUB/gHBAQICvgEFAroBCgK2AQ0CswERAhMBAQCaABQCDQEGAJkAFAIKAQoAlwAWAgUBDgCXABYCAgESAJYAFwL9ABcAlAAYAvkAHACTABgC9QAhAJIAGQLvACcAkAAaAusALACPABsC5QAyAI4AGwLgADgAjQAcAtoAPgCLAB0C1ABFAIoAHgLMAE0AiQAeAsYAVACHACACvQBdAIYAIAK0AGcAhQAhAqgAcwCDACICmACEAIIAIwJvAK0AgQAkAm4ArgB/ACUCbwCuAH4AJgJvAK4AfQAmAm8ArwB7ACgCbwCwAHkAKAJwALAAdwAqAm8AsQB2ACsCbwCxAHUAKwJvALIAcwAtAm8AswBxAC4CbgC0AG8ALwJvALQAbgAwAm4AtgBrADICbQC3AGoAMgJuALgAZwA0Am0AuQBlADYCbAC6AGQANgJtALsAYQA4AmwAvQBeADoCawC+AF0AOgJrAMAAWgA8AmoAwgBXAD4CaQDDAFUAQAJpAMQAUgBCAmgAxgBQAEICaADIAE0ARAJnAMoASgBGAmcAywBHAEgCZgDOAEIASwJlANAAPwBMAmUA0wA7AE4CZQDUADcAUQJkANcAMwBTAmMA2wAtAFYCYwDdACgAWQJiAOIAIABdAmEA5wAXAGICYQDxAAYAaQJgAGEDXwBiA18AYgNeAGMDXgBjA10AZANcAGUDXABlA1sAZwNaAGcDWQBoA1gAaQNYAGkDVwBrA1UAbANVAGwDVABuA1IAbwNSAHADUABxA08AcwNOAHMDTQB1A0sAdwNJAHkDRwB7A0UAfANEAH4DQgCBAz8AgwM9AIUDOwCIAzcAiwM1AI4DMQCSAy0AlgMpAJsDJAChAx0AqAMVAFMC'

let cachedMask: Uint8Array | null = null

/**
 * Returns a 960×614 Uint8Array where 1 = fish, 0 = outside/background.
 * Generated from the official template and cached in memory.
 */
export function getFishSilhouetteMask(): Uint8Array {
  if (cachedMask) return cachedMask
  const bin = atob(MASK_RLE_B64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  const runs = new Uint16Array(bytes.buffer)

  const w = TEMPLATE_CANONICAL.fish.width
  const h = TEMPLATE_CANONICAL.fish.height
  const mask = new Uint8Array(w * h)

  let ptr = 0
  let val = 0
  for (let i = 0; i < runs.length; i++) {
    const count = runs[i]
    if (val === 1) {
      mask.fill(1, ptr, ptr + count)
    }
    ptr += count
    val = val === 0 ? 1 : 0
  }

  cachedMask = mask
  return cachedMask
}
